
init:
  - git config --global core.autocrlf input

clone_folder: C:\projects\bkdecmd
shallow_clone: true

matrix:
  fast_finish: false

platform:
  - x86
  - x64

configuration:
  - Debug
  - Release

# See https://www.appveyor.com/docs/windows-images-software/
environment:
  matrix:
    - toolchain: msvc22
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2022

build:
  project: bkdecmd.sln

test_script:
  cmd: |
    cd %APPVEYOR_BUILD_FOLDER%
    if %PLATFORM% == "x86" (
      set RUNPATH=%CONFIGURATION%
    ) else (
      set RUNPATH=x664\%CONFIGURATION%
    )
    %RUNPATH%\bkdecmd.exe i images\ANDOS330.IMG
    %RUNPATH%\bkdecmd.exe l images\ANDOS330.IMG
    %RUNPATH%\bkdecmd.exe lr images\ANDOS330.IMG
