name: push-matrix

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      matrix:
        config:
        - name: "Ubuntu latest GCC"
          os: ubuntu-latest
          cc: "gcc"
          cxx: "g++"
        - name: "Ubuntu latest Clang"
          os: ubuntu-latest
          cc: "clang"
          cxx: "clang++"
        - name: "macOS latest"
          os: macos-latest
          cc: "clang"
          cxx: "clang++"
      fail-fast: false

    steps:
    - uses: actions/checkout@v3

    - name: Build
      env:
        CC: ${{ matrix.config.cc }}
        CXX: ${{ matrix.config.cxx }}
      run: |
        make
        chmod +x ./bkdecmd

    - name: Test
      run: |
        ./bkdecmd i ./images/ANDOS330.IMG
        ./bkdecmd l ./images/ANDOS330.IMG
        ./bkdecmd lr ./images/ANDOS330.IMG
        ./bkdecmd lr ./images/AODOS.IMG
        ./bkdecmd lr ./images/BK_SYS.DSK
        ./bkdecmd lr ./images/CSIDOS.IMG
        ./bkdecmd lr ./images/MKDOS315.IMG
        ./bkdecmd lr ./images/NORD_1.bkd
        ./bkdecmd lm ./images/ANDOS330.IMG
        ./bkdecmd lm ./images/AODOS.IMG
        ./bkdecmd lm ./images/BK_SYS.DSK
        ./bkdecmd lm ./images/CSIDOS.IMG
        ./bkdecmd lm ./images/MKDOS315.IMG
        ./bkdecmd lm ./images/NORD_1.bkd
        ./bkdecmd lm -sha1 ./images/ANDOS330.IMG
        ./bkdecmd lm -sha1 ./images/AODOS.IMG
        ./bkdecmd lm -sha1 ./images/BK_SYS.DSK
        ./bkdecmd lm -sha1 ./images/CSIDOS.IMG
        ./bkdecmd lm -sha1 ./images/MKDOS315.IMG
        ./bkdecmd lm -sha1 ./images/NORD_1.bkd
